version: "3.0"

services:
  #
  #   The Oracle Traffic Director Servers
  #    
  otdfmw:
    image: ${DC_REGISTRY_OTD}/oracle/otd:${DC_OTD_VERSION}
    container_name: otdfmw
    command: /bin/bash -c "sleep 5s; /opt/oracle/dockertools/crDomain.sh"
    ports:
      - "${DC_ADMINPORT}:${DC_ADMINPORT}"
      - "${DC_OTD_SERVERPORT}:${DC_OTD_SERVERPORT}"
      - "${DC_NM_PORT}:${DC_NM_PORT}"
    environment:
      - SCRIPT_HOME=${DC_SCRIPT_HOME}
      - INT_ORACLE_HOME=${DC_INT_ORACLE_HOME}
      - WL_HOME=${DC_WL_HOME}
      - WLST_HOME=${DC_WLST_HOME}
      - MW=${DC_MW}
      - DOMAIN_BASE=${DC_DOMAIN_BASE}
      - APPLICATION_BASE=${DC_APPLICATION_BASE}
      - APP_VZ=${DC_APP_VZ}
      - TEMPLATE=${DC_TEMPLATE}
      - DOMAIN_NAME=${DC_DOMAIN_NAME}
      - AS_NAME=${DC_AS_NAME}
      - ADM_USER=${DC_ADM_USER}
      - ADM_PWD=${DC_ADM_PWD}
      - ADMINPORT=${DC_ADMINPORT}
      - ADMINPORTSSL=${DC_ADMINPORTSSL}
      - AS_HOST=${DC_AS_HOST}
      - MACHINE_NAME=${DC_MACHINE_NAME}
      - NM_LISTENADDRESS=${DC_NM_LISTENADDRESS}
      - NM_TYPE=${DC_NM_TYPE}
      - NM_PORT=${DC_NM_PORT}
      - NM_USERNAME=${DC_NM_USERNAME}
      - NM_PWD=${DC_NM_PWD}
      - OTD_CONFIGNAME=${DC_OTD_CONFIGNAME}
      - OTD_SERVERNAME=${DC_OTD_SERVERNAME}
      - OTD_SERVERPORT=${DC_OTD_SERVERPORT}
      - OTD_ORIGINSERVER=${DC_OTD_ORIGINSERVER}
    volumes:
      - ${DC_DDIR_OTD}:/opt/oracle/user_projects


